# Generated by Django 3.2.11 on 2022-03-12 09:12

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AqiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.FloatField()),
                ('aqi_data', jsonfield.fields.JSONField()),
            ],
        ),
    ]
